### ISSUE TITLE
First time using custom userscripts, can't get replacement to function

### ISSUE THREAD

**Issue by asorel1942** [theborg3of5/Userscripts#10]
I am attempting to use your extension to replace the main domain of a URL (weaponsman.com) with a new version (weaponsman.looserounds.com), but after configuring the script I can't get it to work. I assume this is because I input the settings incorrectly, would you be able to assist? Script pasted below:

// ==UserScript==
// @name         URL Replacer/Redirector
// @namespace    https://github.com/theborg3of5/Userscripts/
// @version      1.1
// @description  Redirect specific sites by replacing part of the URL.
// @author       Gavin Borg
// @match        https://greasyfork.org/en/scripts/403100-url-replacer-redirector
// @match        https://weaponsman.com/*
// @match        http://weaponsman.com/*
// @grant        GM_getValue
// @grant        GM_setValue
// ==/UserScript==

(function() {
    'use strict';

    // Initial creation of settings structure if it doesn't exist
    if(!GM_getValue("replaceTheseStrings")) {
        GM_setValue("replacePrefix", "http://");
        GM_setValue("replaceSuffix", ".com");
        GM_setValue("replaceTheseStrings", {"weaponsman": "weaponsman.looserounds"});
        console.log("Created settings structure");
    }

    // Prefix/suffix apply to both sides
    var replacePrefix = GM_getValue("replacePrefix");
    var replaceSuffix = GM_getValue("replaceSuffix");
    var replaceAry = GM_getValue("replaceTheseStrings");
//     console.log(replacePrefix, replaceSuffix, replaceAry);

    var newURL = window.location.href;
    for(var key in replaceAry) {
        var toReplace = replacePrefix + key + replaceSuffix;
        var replaceWith = replacePrefix + replaceAry[key] + replaceSuffix;

        // Use a RegEx to allow case-insensitive matching
        toReplace = new RegExp(escapeRegex(toReplace), "i");

        newURL = newURL.replace(toReplace, replaceWith);
    }
//     console.table({"Original URL":window.location.href, "New URL":newURL});

    if(window.location.href !== newURL) {
        window.location.replace(newURL);
    }
})();

// From https://stackoverflow.com/questions/3561493/is-there-a-regexp-escape-function-in-javascript/3561711#3561711
function escapeRegex(string) {
    return string.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
}

**Comment by theborg3of5** [comment]
It looks like you've at least got it set up to run on the right page, but I'd need to see the settings (the JSON from your script manager's storage area, looks something like the "Example" section on the [readme page](https://github.com/theborg3of5/Userscripts/tree/master/urlReplacerRedirector)) to help you out.

Note that the prefix/suffix in the settings need to be part of both the old and new URLs for it to work.

**Comment by theborg3of5** [comment]
Closing due to non-response, feel free to reopen with more info later.
