### ISSUE TITLE
youtubeRSSExport activation problem

### ISSUE THREAD

**Issue by sardiax** [theborg3of5/Userscripts#11]
Running Tampermonkey on Firefox 90 and youtubeRSSExport wouldn't activate.
After adding a * wildcard at the end of @match condition (https//www.youtube.com/) it showed up in the extension menu and seemed to be working properly.

**Comment by theborg3of5** [comment]
Interesting, there must be a little extra on the end of that URL for some people. Adding the wildcard doesn't appear to break anything, so I've done so in commit 84422ec.
