### ISSUE TITLE
New feedly selectors for dec-2022

### ISSUE THREAD

**Issue by njascgil** [theborg3of5/Userscripts#16]
I noticed that [feedlyOpenInBackground.user.js] appeared to have stopped working since yesterday (december 6th, 2022).

After a few short tests, it appears that these selectors cover most of what is now required:

`var selectors = ['#EntryTitleLink-selected','a.Article__title'];`

I didn't test them extensively, but all my personal usual usage scenarios are ok.

**Comment by theborg3of5** [comment]
Thanks for the info! Should be fixed in script version 1.4.
