### ISSUE TITLE
New Feedly selectors for may 2023

### ISSUE THREAD

**Issue by njascgil** [theborg3of5/Userscripts#18]
Hi!
This time I fooled up the pull request... Feel free to delete it, if possible.

However, here are the new selectors which appear to be working fine on my side:
var selectors = ['a.EntryTitleLink--selected','a.Article__title'];
(the first one is now a class, not an id)

Regards

**Comment by theborg3of5** [comment]
Much appreciated! Just dug thru Feedly's source and confirmed that those are our best options, new version coming with those shortly.

As for deleting the pull request - I believe that's [up to you](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/deleting-and-restoring-branches-in-a-pull-request), I don't appear to have an option for it.
