### ISSUE TITLE
Export creates wrong/invalid URLs

### ISSUE THREAD

**Issue by markrjackson** [theborg3of5/Userscripts#3]
Your script generates the wrong URLs in the output. Open the export file and try the links generated. For example:

Your script outputs this:
`xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCLA_DiR1FfKNvjuUpBHmylQ/videos"`

Should be this instead:
`xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCLA_DiR1FfKNvjuUpBHmylQ"`

**Comment by theborg3of5** [comment]
I just subscribed to NASA's channel and used the button, and the output was the same as your second link. Was this from the YouTube homepage or somewhere else?

**Comment by markrjackson** [comment]
Homepage, left column

**Comment by theborg3of5** [comment]
Huh. The script basically just looks at the links (with id="endpoint") in the subscriptions section of the sidebar, and uses the channel IDs there to generate the URLs. Can you look at your sidebar's NASA link and see if it has an extra "/videos" on the end? Otherwise I'm not sure where that extra bit is coming from.

**Comment by markrjackson** [comment]
I have a bunch of subscriptions and they all export the same with the "/videos" part on the end. I guess I can just manually edit the export from now on. Thanks anyway for looking into it.

**Comment by markrjackson** [comment]
If it helps, I just grabbed this from the homepage source code which shows the "/videos" part:

`<a id="endpoint" class="yt-simple-endpoint style-scope ytd-guide-entry-renderer" tabindex="-1" role="tablist" title="NASA" href="https://www.youtube.com/channel/UCLA_DiR1FfKNvjuUpBHmylQ/videos" it-origin="https://www.youtube.com/channel/UCLA_DiR1FfKNvjuUpBHmylQ">
</a>`

The `it-origin` shows the channel without the "/videos".

**Comment by theborg3of5** [comment]
Huh, that's exactly where it's coming from, then! Mine only have an href, (without the "/videos" bit), not an it-origin. Maybe Google's running some A/B testing or some other slow roll-out.

Regardless, the "/videos" bit really should appear as part of an ID, so I should be able to trim it out if it's there from inside the script. Let me see what I can do.

**Comment by theborg3of5** [comment]
And I believe that should fix it for you - let me know if not!

**Comment by markrjackson** [comment]
Beautiful! Absolutely perfect now, thanks man!
