### ISSUE TITLE
youtubeRSSExport no "Export" button

### ISSUE THREAD

**Issue by eric-bixby** [theborg3of5/Userscripts#4]
I'm not getting an "Export" button.

I checked the web page source for YouTube.com and I don't see "yt-formatted-string#guide-section-title".

**Comment by ngirard** [comment]
I couldn't tell if it would solve @eric-bixby's problem, but I ran into the same problem and can tell what solved mine.
Within the code is the label "Subscriptions" hardwired ; but depending on the user's locale, the label differs.
For instance, when in French locale, the label is "Abonnements".
When I replaced the line
```
        if(sectionLabels[i].innerHTML === "Subscriptions") {
```
with
```
        if(sectionLabels[i].innerHTML === "Abonnements") {
```
The export button appeared.
Obviously, you might want to hook more robustly than on such label.

Cheers, and thanks for your work !

**Comment by eric-bixby** [comment]
It's not a locale issue because I'm in the US.

Anyway, I withdraw my issue.  It was a little slow, but I just manually added each YouTube channel into Feedly.

**Comment by ngirard** [comment]
> Anyway, I withdraw my issue. It was a little slow, but I just manually added each YouTube channel into Feedly.

Could you please reopen the issue, so that the author can apply my fix ?

Thanks in advance.

**Comment by eric-bixby** [comment]
Wow, that was fast, thanks!

**Comment by theborg3of5** [comment]
Unfortunately YouTube's pages are very, shall we say, "generated" and there's very little that I've found to uniquely identify the Subscriptions section (at least in the versions of the page I'm being served). If you see something I've missed, please let me know!

In the meantime, I've just added (v1.2) a fallback method for determining where to put the button - now it will drop it in the second section in the sidebar (as the first section's header is hidden). That should help everyone outside of my home en-US locale. :)

**Comment by ngirard** [comment]
Great, thanks !
