### ISSUE TITLE
No export button

### ISSUE THREAD

**Issue by taraletti** [theborg3of5/Userscripts#5]
Hi there! I just find the code, install it and I can't find the export button. I put youtube in English (US) and doesn't appear. I'm very noob on this things and I would love to make it work so I can see youtube in my symbian phone.

function findSpotToPutButton() {
    var sectionLabels = document.querySelectorAll("yt-formatted-string#guide-section-title");

    // First try to find the "Subscriptions" section. Won't work outside of an en-US locale.
    var subscriptionsText = "Subscriptions";
    for(var i = 0; i < sectionLabels.length; i++) {
        if(sectionLabels[i].innerHTML === subscriptionsText) {
            return sectionLabels[i].parentElement;
        }
    }

    // If that fails, just put it in the second section (first one's header is hidden).
    return sectionLabels[1].parentElement;
}

I don't understand what to do in the "If that fails" section.  I have to copy all this too?

 var subscriptionsText = "Subscriptions";
    for(var i = 0; i < sectionLabels.length; i++) {
        if(sectionLabels[i].innerHTML === subscriptionsText) {
            return sectionLabels[i].parentElement;
        }
    }

I did that and doesn't appear. I'm using Vivaldi that works with chromium

**Comment by taraletti** [comment]
Quick update, made it with chromium browser. But not good, when I click to export I go to the first sub channel of my account.. What should I do?

**Comment by taraletti** [comment]
update again...now doesn't appear on chromium....

**Comment by nbourre** [comment]
Same thing here. I don't see the **Export button**.

**Comment by sheikhani** [comment]
Doesn't work me either.

**Comment by theborg3of5** [comment]
Unfortunately it seems that the sidebar is fluctuating too much for a button to live there reliably (or else you're all getting served some alternative version of the page, which wouldn't surprise me given Google's history with A/B tests).

I'm going to look into triggering the download some other way (probably via an extension menu in TamperMonkey, etc.) soon.
