### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by vecuccio** [theborg3of5/Userscripts#6]
I clicked 'show more' to load all the subbed channels into the side bar, then clicked EXPORT. And all that happened was that it loaded the channel that was at the top of the list of subbed channels into the main Youtube window.
I have NoScript set to allow everything, and Ad-Guard turned off. I can't think what else to try.

**Comment by theborg3of5** [comment]
Should hopefully be resolved by latest commit (00d5212, version 1.3). Feel free to reopen if that doesn't fix it.

**Comment by vecuccio** [comment]
Greasemonkey hadn't autoupdated the script since 28th Feb. I managed to force the script to update and your fix works perfectly. Thankyou.
