### ISSUE TITLE
I just installed greasemokey and your Youtube/OPML script - but get 'GM_registerMenuCommand'

### ISSUE THREAD

**Issue by pperrin** [theborg3of5/Userscripts#9]
Script error in [Greasemonkey script https://github.com/theborg3of5/Userscripts//Export YouTube Subscriptions to RSS OPML; version 1.5]:
ReferenceError: GM_registerMenuCommand is not defined

Running on an ancient laptop, in firefox 88.0 (32-bit)

ps. I switched to violentmonkey and it seems to work fine.

**Comment by theborg3of5** [comment]
Yeah, seems that Greasemonkey doesn't support the same GM_* functions, instead requiring their GM.* equivalents. I did just push out an update to the script that should allow Greasemonkey to handle it, but I prefer Tampermonkey myself.
